# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('caption', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('folder', 'folder'), ('card', 'card'), ('list', 'list'), ('report', 'report')], max_length=6)),
                ('parent_code', models.IntegerField()),
                ('module', models.CharField(max_length=100)),
                ('access_level', models.IntegerField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'sys_menu',
                'managed': True,
            },
        ),
    ]
